GET http://localhost:3000/tasks
###
GET http://localhost:3000/tasks/643cf37c0b826e94b4e32a14
###
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "name": "Take out trash",
    "assigned_to": "Liam",
    "priority": "false"
}
###
DELETE  http://localhost:3000/tasks/643cf37c0b826e94b4e32a14
###

DELETE  http://localhost:3000/tasks/deleteAll
###




GET http://localhost:3000/users
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Liam",
    "color": "Red"
}
###